Repository iRobsc/Dinner-planner, pull requests merged in 2018-03, with the labels that each got.

#14 Add root component
  src/components/App.js
  src/index.js
Labels: feature, lab 4

#17 ✅ Add components for dinner buttons
  src/components/DinnerButton.js
  src/components/DinnerButtonLink.js
  src/css/buttons.scss
  src/css/index.scss
Labels: feature, lab 4

#18 Add Welcome component and remove onClick for DinnerButtonLink
  src/components/App.js
  src/components/DinnerButtonLink.js
  src/components/Welcome.js
  src/index.html
Labels: feature, lab 4

#20 Basic improvements
  src/components/App.js
  src/components/Welcome.js
  src/index.html
  src/index.js
  src/pages/WelcomePage.js
Labels: lab 4

#21 Babel updates
  .babelrc
  .eslintrc.js
  package-lock.json
  package.json
Labels: lab 4

#22 Update DinnerButtonLink
  .eslintrc.js
  src/components/DinnerButtonLink.js
Labels: lab 4

#23 Add FoodItem component
  src/components/FoodItem.js
  src/css/FoodItem.scss
  src/css/_food-grid.scss
Labels: lab 4

#24 Add Searchbar Component
  src/components/Searchbar.js
  src/css/Searchbar.scss
  src/css/index.scss
Labels: lab 4

#25 Add layout components
  .babelrc
  .eslintrc.js
  package-lock.json
  package.json
  src/layouts/MainLayout.js
  src/pages/AppRoute.js
Labels: lab 4

#26 Implement sidebar and the sidebar item
  src/components/DinnerButtonLink.js
  src/components/Sidebar.js
  src/components/SidebarItem.js
  src/components/Welcome.js
  src/css/Sidebar.scss
  src/css/index.scss
Labels: feature, lab 4

#27 Add MyDinnerTitle
  src/components/MyDinnerTitle.js
  src/css/MyDinnerTitle.scss
  src/css/_my-dinner.scss
Labels: lab 4

#29 Add state to App
  .eslintrc.js
  src/components/App.js
  src/components/Sidebar.js
  src/layouts/MainLayout.js
  src/pages/AppRoute.js
Labels: lab 4

#30 Create a component for ingredientlist
  src/components/Ingredientlist.js
  src/css/DishContent.scss
  src/css/Ingredientlist.scss
  src/css/index.scss
Labels: feature, lab 4

#31 Implement searching
  src/components/DishSelect.js
  src/components/FoodItem.js
  src/components/Searchbar.js
  src/containers/App.js
  src/containers/DishSearchContainer.js
  src/index.js
  src/pages/SearchPage.js
  src/utils/cache.js
  src/utils/getAllDishes.js
Labels: lab 4

#32 Fix food grid CSS
  src/components/DishSelect.js
  src/css/DishSelect.scss
  src/css/index.scss
Labels: lab 4

#33 Add MyDinner component
  src/components/Sidebar.js
  src/containers/App.js
  src/css/MyDinner.scss
  src/css/index.scss
  src/layouts/ResultLayout.js
  src/pages/MyDinnerPage.js
  src/utils/getTotalMenuPrice.js
Labels: lab 4

#35 Search fix
  src/components/DishSelect.js
  src/containers/DishSearchContainer.js
  src/pages/SearchPage.js
Labels: lab 4

#36 Add dish details page with all the functionality
  src/components/DishDetails.js
  src/components/Ingredientlist.js
  src/containers/App.js
  src/containers/DishDetailsContainer.js
  src/css/Ingredientlist.scss
  src/css/_dish-content.scss
  src/pages/DishDetailsPage.js
  src/utils/getDish.js
Labels: feature, lab 4

#51 Recipepage
  src/components/RecipeItem.js
  src/components/RecipeList.js
  src/css/Recipes.scss
  src/css/index.scss
  src/pages/RecipesPage.js
Labels: feature, lab 4

#52 🐛 Remove old import in index.scss
  src/css/index.scss
Labels: bug, lab 4

#55 🚧 Improve error handling in DishSelect
  src/components/DishSelect.js
  src/containers/DishSearchContainer.js
Labels: enhancement, lab 4

#56 :bug: Fix error message when dish can't load
  src/containers/DishDetailsContainer.js
Labels: bug, lab 4

#57 Add home button to 404 page
  src/css/NoMatch.scss
  src/pages/NoMatchPage.js
Labels: enhancement, lab 4
